version: '3'

services:

  frontend-production:
    container_name: frontend-production
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'

networks:
    default:
        external:
            name: nginx-proxy